### ISSUE TITLE
Builds Broken

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#52]
I went to compile with maven this evening to test a fix and I received an error.  Is this related to openhab 2.1 going live?  I am not sure if there is something we have to update or if we need to merge the released 2.1 tree into our fork?  Or something is now wrong on my side only?

```
 mvn clean install
[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.openhab.binding:org.openhab.binding.omnilink:2.1.0-SNAPSHOT @ /home/broconne/code/openhab2-addons/addons/binding/org.openhab.binding.omnilink/pom.xml
[INFO] Fetching p2.index from http://download.eclipse.org/smarthome/updates-stable/ (0B at 0B/s)
[INFO] Adding repository http://download.eclipse.org/smarthome/updates-stable
[INFO] Fetching p2.index from https://dl.bintray.com/openhab/p2/openhab-core/2.1.x/ (0B of 172B at 0B/s)
[INFO] Adding repository https://dl.bintray.com/openhab/p2/openhab-core/2.1.x
[ERROR] Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-openhab-core' from location https://dl.bintray.com/openhab/p2/openhab-core/2.1.x: Artifact not found: https://dl.bintray.com/openhab/p2/openhab-core/2.1.x/content.xml.xz. -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-openhab-core' from location https://dl.bintray.com/openhab/p2/openhab-core/2.1.x
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Failed to load p2 repository with ID 'p2-openhab-core' from location https://dl.bintray.com/openhab/p2/openhab-core/2.1.x
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:302)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.gatherExternalInstallableUnits(TargetPlatformFactoryImpl.java:270)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:176)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:128)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.createTargetPlatform(TargetPlatformFactoryImpl.java:1)
	at org.eclipse.tycho.p2.manager.ReactorRepositoryManagerImpl.computePreliminaryTargetPlatform(ReactorRepositoryManagerImpl.java:84)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.computePreliminaryTargetPlatform(P2DependencyResolver.java:223)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:109)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
Caused by: org.eclipse.equinox.p2.core.ProvisionException: Artifact not found: https://dl.bintray.com/openhab/p2/openhab-core/2.1.x/content.xml.xz.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:428)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCacheFromFile(CacheManager.java:132)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.getLocalFile(XZedSimpleMetadataRepositoryFactory.java:56)
	at org.eclipse.equinox.internal.p2.metadata.repository.XZedSimpleMetadataRepositoryFactory.load(XZedSimpleMetadataRepositoryFactory.java:78)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53)
	at org.eclipse.tycho.p2.target.TargetPlatformFactoryImpl.loadMetadataRepository(TargetPlatformFactoryImpl.java:298)
	... 22 more
Caused by: java.io.FileNotFoundException: https://dl.bintray.com/openhab/p2/openhab-core/2.1.x/content.xml.xz
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:297)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.checkException(FileReader.java:478)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.sendRetrieveRequest(FileReader.java:435)
	at org.eclipse.equinox.internal.p2.transport.ecf.FileReader.readInto(FileReader.java:358)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:101)
	at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryTransport.download(RepositoryTransport.java:156)
	at org.eclipse.equinox.internal.p2.repository.CacheManager.updateCache(CacheManager.java:402)
	... 32 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by boc-tothefuture** [comment]
@digitaldan and @craigham  -
   When you get a chance can either of you verify you are seeing this when you build with maven?  If it is just me, I will go done a different troubleshooting steps.

**Comment by craigham** [comment]
@boc-tothefuture I am getting the same errors.

I noticed 2.2 was just released for dev.  I'll see if I can get it working.

**Comment by craigham** [comment]
ok, if you get latest I have brought it up to date with the latest from openhab.

the binding now builds with

mvn  install -Dreport.fail.on.error=false

the -D just let's it succeed on the code analysis tests.  Some work to do there to get code up to standards.

**Comment by craigham** [comment]
I've been trying to get all up to date w 2.2 snapshot.

When I try and run discovery, I get this error, any ideas?

It seems to be getting a Message.MESG_TYPE_NEG_ACK: in the MessageFactory.fromBytes method within jomnilink.

`2017-07-01 06:13:51.313 [DEBUG] [b.o.d.OmnilinkDiscoveryService:66   ] - Starting scan
2017-07-01 06:13:51.415 [ERROR] [.o.b.o.d.ObjectPropertyRequest:61   ] - Error retrieving object propertiescom.digitaldan.jomnilinkII.OmniInvalidResponseException: null
	at com.digitaldan.jomnilinkII.Connection.reqObjectProperties(Connection.java:538)
	at org.openhab.binding.omnilink.handler.OmnilinkBridgeHandler.reqObjectProperties(OmnilinkBridgeHandler.java:460)
	at org.openhab.binding.omnilink.discovery.ObjectPropertyRequest$1.computeNext(ObjectPropertyRequest.java:51)
	at org.openhab.binding.omnilink.discovery.ObjectPropertyRequest$1.computeNext(ObjectPropertyRequest.java:1)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.openhab.binding.omnilink.discovery.OmnilinkDiscoveryService.discoverAreas(OmnilinkDiscoveryService.java:205)
	at org.openhab.binding.omnilink.discovery.OmnilinkDiscoveryService.startScan(OmnilinkDiscoveryService.java:70)
	at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:199)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:382)
	at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:358)
`

**Comment by boc-tothefuture** [comment]
Must be a defect in my iterator.  I will take a look shortly.

**Comment by boc-tothefuture** [comment]
Closing this and opened two related defects:
#55  and #54
