### ISSUE TITLE
Discovery throwing exception

### ISSUE THREAD

**Issue by boc-tothefuture** [QuailAutomation/openhab2-addons#55]
@craigham reported the following exception

```

2017-07-01 06:13:51.313 [DEBUG] [b.o.d.OmnilinkDiscoveryService:66 ] - Starting scan 2017-07-01 06:13:51.415 [ERROR] [.o.b.o.d.ObjectPropertyRequest:61 ] - Error retrieving object propertiescom.digitaldan.jomnilinkII.OmniInvalidResponseException: null at com.digitaldan.jomnilinkII.Connection.reqObjectProperties(Connection.java:538) at org.openhab.binding.omnilink.handler.OmnilinkBridgeHandler.reqObjectProperties(OmnilinkBridgeHandler.java:460) at org.openhab.binding.omnilink.discovery.ObjectPropertyRequest$1.computeNext(ObjectPropertyRequest.java:51) at org.openhab.binding.omnilink.discovery.ObjectPropertyRequest$1.computeNext(ObjectPropertyRequest.java:1) at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) at org.openhab.binding.omnilink.discovery.OmnilinkDiscoveryService.discoverAreas(OmnilinkDiscoveryService.java:205) at org.openhab.binding.omnilink.discovery.OmnilinkDiscoveryService.startScan(OmnilinkDiscoveryService.java:70) at org.eclipse.smarthome.config.discovery.AbstractDiscoveryService.startScan(AbstractDiscoveryService.java:199) at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScan(DiscoveryServiceRegistryImpl.java:382) at org.eclipse.smarthome.config.discovery.internal.DiscoveryServiceRegistryImpl.startScans(DiscoveryServiceRegistryImpl.java:358)
```

**Comment by craigham** [comment]
this now works.
