### ISSUE TITLE
Error in log file often Isy 2.2

### ISSUE THREAD

**Issue by robertw** [QuailAutomation/openhab2-addons#93]
Hi Craig : 

Here is the log with the error it seems to recover but it does happen when heavy usage of the binding..

 2017-08-16 15:28:39.067 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node 'n/a' got control message '_1' action '0'

2017-08-16 15:28:39.069 [TRACE] [sy.internal.IsyWebSocketSubscription] - Parsing message: [<?xml version="1.0"?><Event seqnum="338" sid="uuid:158"><control>_1</control><action>6</action><node></node><eventInfo><var type="2" id="4"><val>0</val><ts>20170816 11:28:33</ts></var></eventInfo></Event>]

2017-08-16 15:28:39.072 [DEBUG] [sy.internal.IsyWebSocketSubscription] - Node 'n/a' got control message '_1' action '6'

2017-08-16 15:28:39.074 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - need to find variable handler, id is: 4, val: 0

2017-08-16 15:28:39.076 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - find thing handler for id: 4, type: 2

2017-08-16 15:28:39.078 [TRACE] [binding.isy.handler.IsyBridgeHandler] - checking thing to see if match, id: 10 , type: 2

2017-08-16 15:28:39.080 [WARN ] [.internal.IsyWebSocketSubscription$1] - Unhandled Error (closing connection)

java.lang.NullPointerException

	at org.openhab.binding.isy.handler.IsyBridgeHandler$1.onVariableChanged(IsyBridgeHandler.java:134)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.openhab.binding.isy.internal.IsyWebSocketSubscription.parseXml(IsyWebSocketSubscription.java:122)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.openhab.binding.isy.internal.IsyWebSocketSubscription.access$0(IsyWebSocketSubscription.java:102)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.openhab.binding.isy.internal.IsyWebSocketSubscription$1.onWebSocketText(IsyWebSocketSubscription.java:45)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:65)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:161)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:632)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:480)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.19.v20160908]

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[82:org.eclipse.jetty.util:9.2.19.v20160908]

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[82:org.eclipse.jetty.util:9.2.19.v20160908]

	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]

2017-08-16 15:28:39.089 [ERROR] [sy.internal.IsyWebSocketSubscription] - Error with websocket communication

java.lang.NullPointerException

	at org.openhab.binding.isy.handler.IsyBridgeHandler$1.onVariableChanged(IsyBridgeHandler.java:134)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.openhab.binding.isy.internal.IsyWebSocketSubscription.parseXml(IsyWebSocketSubscription.java:122)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.openhab.binding.isy.internal.IsyWebSocketSubscription.access$0(IsyWebSocketSubscription.java:102)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.openhab.binding.isy.internal.IsyWebSocketSubscription$1.onWebSocketText(IsyWebSocketSubscription.java:45)[215:org.openhab.binding.isy:2.2.0.201708052134]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:128)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:65)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:122)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:161)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:309)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:214)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:258)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:632)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:480)[87:org.eclipse.jetty.websocket.common:9.2.19.v20160908]

	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)[70:org.eclipse.jetty.io:9.2.19.v20160908]

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)[82:org.eclipse.jetty.util:9.2.19.v20160908]

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)[82:org.eclipse.jetty.util:9.2.19.v20160908]

	at java.lang.Thread.run(Thread.java:748)[:1.8.0_144]

2017-08-16 15:28:39.120 [DEBUG] [binding.isy.handler.IsyBridgeHandler] - Received onDeviceOffLine message

**Comment by craigham** [comment]
@robertw The latest build should address the error.

**Comment by robertw** [comment]
Thank you will give it a try

**Comment by robertw** [comment]
the binding still shows version  1 how can i be sure the market version is the most current....

error on restart :Isy 
           2017-08-23 12:49:25.117 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null

java.lang.NullPointerException: null

	at org.openhab.binding.isy.handler.IsyDeviceHandler.handleCommand(IsyDeviceHandler.java:105) [225:org.openhab.binding.isy:2.2.0.201708191547]

	at org.eclipse.smarthome.core.thing.binding.BaseThingHandler.channelLinked(BaseThingHandler.java:204) [105:org.eclipse.smarthome.core.thing:0.9.0.201708151402]

	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:264) [105:org.eclipse.smarthome.core.thing:0.9.0.201708151402]

	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:304) [105:org.eclipse.smarthome.core.thing:0.9.0.201708151402]

	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1) [105:org.eclipse.smarthome.core.thing:0.9.0.201708151402]

	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50) [98:org.eclipse.smarthome.core:0.9.0.201708151402]

	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:193) [98:org.eclipse.smarthome.core:0.9.0.201708151402]

	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1) [98:org.eclipse.smarthome.core:0.9.0.201708151402]

	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181) [98:org.eclipse.smarthome.core:0.9.0.201708151402]

	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:?]

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:?]

	at java.lang.Thread.run(Thread.java:748) [?:?]

thank you

**Comment by robertw** [comment]
additional errors 
==> /var/log/openhab2/openhab.log <==

2017-08-23 13:19:28.743 [ERROR] [sy.internal.IsyWebSocketSubscription] - Error parsing message [<?xml version="1.0"?><Event seqnum="496" sid="uuid:32"><control>_1</control><action>3</action><node></node><eventInfo>[ELK 1   0  0] Area : Isa&Robert House : Ready To Arm (2/1/0)</eventInfo></Event>]

2017-08-23 13:19:29.242 [ERROR] [sy.internal.IsyWebSocketSubscription] - Error parsing message [<?xml version="1.0"?><Event seqnum="502" sid="uuid:32"><control>_1</control><action>3</action><node></node><eventInfo>[ELK 1   0  0] Area : Isa&Robert House : Not Ready To Arm (2/0/0)</eventInfo></Event>]

2017-08-23 13:19:32.191 [ERROR] [sy.internal.IsyWebSocketSubscription] - Error parsing message [<?xml version="1.0"?><Event seqnum="508" sid="uuid:32"><control>_1</control><action>3</action><node></node><eventInfo>[ELK 1   0  0] Area : Isa&Robert House : Ready To Arm (2/1/0)</eventInfo></Event>]

2017-08-23 13:20:02.889 [ERROR] [sy.internal.IsyWebSocketSubscription] - Error parsing message [<?xml version="1.0"?><Event seqnum="519" sid="uuid:32"><control>_1</control><action>3</action><node></node><eventInfo>[ELK 1   0  0] Area : Isa&Robert House : Not Ready To Arm (2/0/0)</eventInfo></Event>]

2017-08-23 13:20:05.289 [ERROR] [sy.internal.IsyWebSocketSubscription] - Error parsing message [<?xml version="1.0"?><Event seqnum="525" sid="uuid:32"><control>_1</control><action>3</action><node></node><eventInfo>[ELK 1   0  0] Area : Isa&Robert House : Ready To Arm (2/1/0)</eventInfo></Event>]

**Comment by craigham** [comment]
@robertw A lot of these errors could be due to me not shutting down services properly when you upgraded.  Could you try restarting openhab after you uninstall/install via the marketplace binding until I get that resolved?  

Also, could you turn up the debugging to TRACE?  Would add a little more context before the errors.

I will look into why the ELK events are logging errors, though it may be hard to avoid those without ELK support in there.

**Comment by craigham** [comment]
@robertw  it looks to me as though you do have the latest version of the binding.

if you see the line which contains: [225:org.openhab.binding.isy:2.2.0.201708191547]

That states the build was on Aug 19th.  

You can always check that line with this url which should show latest build.  It's somewhat obfuscated, but the date of file (isy 2.2.0) is here:

https://s3-us-west-2.amazonaws.com/craigham-pub

**Comment by ve7gel** [comment]
I too see the Elk errors in my logs, Craig.  Other than adding a little size to the logs they don't seem to be causing any problems so I haven't been worrying about them.  Are they an issue?

**Comment by craigham** [comment]
No, they are really just noise.

**Comment by craigham** [comment]
I just did a new build which hopefully will get rid of those elk errors.  I can't test because I don't have ELK, so please let me know.

I also cleaned up shutdown/restart of the isy binding, so should not see errors utilizing the marketplace upgrade.

thanks

**Comment by craigham** [comment]
haven't had feedback in awhile.  closing.  let me know if needs to be re-opened.
