### ISSUE TITLE
omni: NPE

### ISSUE THREAD

**Issue by craigham** [QuailAutomation/openhab2-addons#97]
@boc-tothefuture I saw the NPE below when I restarted my openhab.  

Before the NPE, I saw this trace which seems applicable.

2017-09-30 10:20:59.007 [WARN ] [link.handler.AbstractOmnilinkHandler] - Received null status update

Do you think we could have the status Optional initialized to empty when an instance is created?  Would this make it easier to know it is valid at all times?

eg
private volatile Optional<T> status;

to
private volatile Optional<T> status = Optional.empty();

`2017-09-30 10:21:00.206 [ERROR] [ome.core.thing.link.ThingLinkManager] - Exception occurred while informing handler: null
java.lang.NullPointerException: null
	at org.openhab.binding.omnilink.handler.AbstractOmnilinkHandler.channelLinked(AbstractOmnilinkHandler.java:75) [229:org.openhab.binding.omnilink:2.2.0.201709181404]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.informHandlerAboutLinkedChannel(ThingLinkManager.java:281) [108:org.eclipse.smarthome.core.thing:0.9.0.201709121704]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:321) [108:org.eclipse.smarthome.core.thing:0.9.0.201709121704]
	at org.eclipse.smarthome.core.thing.link.ThingLinkManager.receiveTypedEvent(ThingLinkManager.java:1) [108:org.eclipse.smarthome.core.thing:0.9.0.201709121704]
	at org.eclipse.smarthome.core.events.AbstractTypedEventSubscriber.receive(AbstractTypedEventSubscriber.java:50) [101:org.eclipse.smarthome.core:0.9.0.201709121704]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:193) [101:org.eclipse.smarthome.core:0.9.0.201709121704]
	at org.eclipse.smarthome.core.internal.events.OSGiEventManager$1.call(OSGiEventManager.java:1) [101:org.eclipse.smarthome.core:0.9.0.201709121704]
	at org.eclipse.smarthome.core.common.SafeMethodCaller$CallableWrapper.call(SafeMethodCaller.java:181) [101:org.eclipse.smarthome.core:0.9.0.201709121704]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
	at java.lang.Thread.run(Thread.java:748) [?:?]`

**Comment by boc-tothefuture** [comment]
@craigham - Sorry.. Somehow I didn't see this for over a month!

From what I can tell, yes going optional.empty() is the right move.

Did you already make a PR or want me to?

**Comment by craigham** [comment]
@boc-tothefuture to be honest I am not sure if I did a PR.  I will take a look and let you know.

**Comment by boc-tothefuture** [comment]
#100 should close this.

**Comment by boc-tothefuture** [comment]
@craigham - you can close this (#100 fixed it)
